apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-catalouge.
  description: Drupal backend website for ST members
spec:
  type: service
  lifecycle: test
  owner: user:mikkeschiren
  annotations:
    backstage.io/techdocs-ref: dir:.
    kraut.se/library-list-site: verksamt-se
